### ISSUE TITLE
หัวข้อทำเกมส์

### ISSUE THREAD

**Issue by Suwannapop** [Suwannapop/ProjectComPro#1]

**Comment by Blackcat2101** [comment]
เกม A-math

**Comment by Suwannapop** [comment]
เกมส์ 24 หรือ เกมส์ 180 iq

**Comment by Fittokung** [comment]
Tetris

**Comment by asporQ** [comment]
minesweeper

**Comment by chananchidaily** [comment]
เกม งู

**Comment by Suwannapop** [comment]
ทำเกมส์ เเนวพิมดีดไหมเเนวเเบบ 
https://zty.pe 
ไหมน่าจะพอได้ดีนะ

**Comment by Fittokung** [comment]
ดีย์ น่าสนใจ

**Comment by Blackcat2101** [comment]
เอาเลยเพื่อน

**Comment by 4z4le4** [comment]
----------------------------------------------------
ชื่อกลุ่ม :  พา c++ ไป skrt 
หัวข้อ : C++Type        
รายละเอียด : 
         Type หมายถึงพิมพ์ เราจะเอา การพิมพ์ออกมาทำในรูปแบบเกม โดยอ้างอิงเกมต้นฉบับมาจาก เกมในตำนานอย่างเกม
//เกมยิงจรวด Galaga //  แต่เปลี่ยนจากการยิงกระสุนออโต้ที่จะทำดาเมจใส่ยานรบ เป็นการพิมพ์คำศัพท์เพิ่งสร้างดาเมจแก่ยานรบ ในแต่ละเวฟนั้นๆ
----------------------------------------------------

**Comment by 4z4le4** [comment]
คร่าวๆนะค้าบบบคุณเพื่อนๆ
