### ISSUE TITLE
ทำ UI

### ISSUE THREAD

**Issue by Suwannapop** [Suwannapop/ProjectComPro#10]

**Comment by 4z4le4** [comment]
c++ จ้าพี่มาแล้วจ๊ะ

**Comment by 4z4le4** [comment]
[UI เกือบเสร็จ.txt](https://github.com/Suwannapop/ProjectComPro/files/10800417/UI.txt)

**Comment by 4z4le4** [comment]
[ซ่อนรหัสผ่านตอนพิมพ์.txt](https://github.com/Suwannapop/ProjectComPro/files/10800535/default.txt)

**Comment by 4z4le4** [comment]
[Menu Look Thung Style.txt](https://github.com/Suwannapop/ProjectComPro/files/10802355/Menu.Look.Thung.Style.txt)

**Comment by 4z4le4** [comment]
[f(higlight) = Look Thung Style.txt](https://github.com/Suwannapop/ProjectComPro/files/10802359/f.higlight.Look.Thung.Style.txt)

**Comment by 4z4le4** [comment]
[password  Look Thung Style.txt](https://github.com/Suwannapop/ProjectComPro/files/10802362/password.Look.Thung.Style.txt)

**Comment by 4z4le4** [comment]
ระบบล็อคอิน หน้าต่างเมนู มีไฮไลน์แล้ว ระบบเลื่อนขึ้นลงเลือกเมนู
[UI =ID & password & UI Meun  demo Look Thung Style.txt](https://github.com/Suwannapop/ProjectComPro/files/10802364/UI.ID.password.UI.Meun.demo.Look.Thung.Style.txt)

**Comment by 4z4le4** [comment]
ระบบเช็คเงินแบบอาเรย์ ทำมาเผื่อทดสอบเฉยๆๆๆๆๆ
[Mony Look Thung Style.txt](https://github.com/Suwannapop/ProjectComPro/files/10802368/Mony.Look.Thung.Style.txt)

**Comment by 4z4le4** [comment]
อัพเดท<br>
ระบบล็อคอินให้ย้อนกลับมาหน้าแรกได้<br>
ระบบคลูดาวน์ให้แสดงข้อความก่อนไปต่อหน้าไป<br>
แก้ระบบล็อคอินที่บัคเวลาออกจากระบบ<br>
[UI backmenu & sleep.txt](https://github.com/Suwannapop/ProjectComPro/files/10807167/UI.backmenu.sleep.txt)

**Comment by 4z4le4** [comment]
เหลือทำระบบย้อนกลับเมนูหลักของ ในส่วนการทำธูรกรรมการเงินต่างๆ (ฝากถอนโอนจ่าย) และแต่งหน้าต่างให้สวยๆค้าบผม

**Comment by 4z4le4** [comment]
เพิ่ม
ระบบย้อนกลับ
ระบบดีเลย์ให้ดูไม่หน่วงมากไป
[ATM DEMO.txt](https://github.com/Suwannapop/ProjectComPro/files/10810668/ATM.DEMO.txt)

**Comment by Delphisss** [comment]
บัค หากไม่มีไอดีในdata แม้รหัสจะถูก แต่โค้ดจะไม่รันต่อ

**Comment by 4z4le4** [comment]
ตอนนนี้กำลังเอาโค้ดขอเพื่อนๆมารวมกันนะครับ

**Comment by 4z4le4** [comment]
หลังจากที่เอาฟังก์ชั่นมารวมกันแล้ว ผมได้ทำการเพิ่มลูกเล่นเข้าไป โดนปรับเมนูให้สมจริงเหมือนตู้ATM อาทิ การกดเมนูขึ้นลงได้ มีการเริ่มไฮไลท์ข้อความ และเพิ่มการวนลูปทำหน้าที่ของโปรแกรมได้เรื่อย ไปแล้วนะครับ

**Comment by 4z4le4** [comment]
ตอนนี้กำลังนั่งแก้ส่วนที่ไม่จำเป็นออกอยู่นะครับ อาทิ การแสดงผลของทศนิยมที่มาเกินไป (1หมื่นตำแหน่ง ที่แสดงออกมา)
บัคของข้อความที่ error รวมถึงการอ่านค่าต่างๆที่โปรแกรมไม่เข้าใจ

**Comment by 4z4le4** [comment]
9/3/2566 ได้นำส่วนของการทำสลิปมบเสร็จมา แต่ยังเจอการทำงานที่ไม่โอเค ดังรูป 
![image](https://user-images.githubusercontent.com/120131543/224075576-f815e4ac-98c1-46d9-915a-9de1b20a9e4c.png)
...กำลังดำเนินการแก้ไข

**Comment by 4z4le4** [comment]
ได้ทำการปรับให้มีการใช้คำสั่ง system("cls") ในส่วนก่อนหน้าการแสดงผลของสลีปใบเสร็จ ดั่งรูป
![image](https://user-images.githubusercontent.com/120131543/224076515-e3df9953-f336-4165-b763-b2de9b8a3d00.png)

ทำให้ได้การแสดงผลดังรูป

![image](https://user-images.githubusercontent.com/120131543/224076322-10b6b409-5871-4805-835f-2cf6f52e643d.png)

**Comment by 4z4le4** [comment]
ในส่วนของการล็อคอินมันบัคเมื่อไม่มีดาต้า ไม่มีการให้ทำการสมัครไอดี
![image](https://user-images.githubusercontent.com/120131543/224083550-e2b9347d-ede3-4e26-8767-37b9bf465b1a.png)

**Comment by 4z4le4** [comment]
ได้ทำการแก้บัคโดยการแก้การเช็คที่อยู่ของไอดีใหม่และเงื่อนที่ใช้ในการเช็ค พบว่ามีการเรียกซ้อนทับจึงแก้ด้วยการปรับให้เหลือการเรียกใช้ของโค้ดในส่วนเดียว
![image](https://user-images.githubusercontent.com/120131543/224083977-2c827c9e-15d1-4d78-8a23-8572a45b7ac3.png)

**Comment by 4z4le4** [comment]
ทำการเพิ่ม ตัวเลือกกลับสู่หน้าเมนูกับฟังก์ชั่นไฮไลน์ เพื่อแก้ปัญหาการอ่านสลีปใบเสร็จ ที่จะหายไปหลังแสดงผล 2 วินาที
![image](https://user-images.githubusercontent.com/120131543/224106581-a32a64a4-9176-4c6e-944f-d275eb73783b.png)

**Comment by 4z4le4** [comment]
เพิ่มส่วนโค้ดที่จำเป็นในการเรียกใช้ฟังก์ชั่นในส่วนของโค้ดการแสดงสลีปใบเสร็จทุกส่วน
![image](https://user-images.githubusercontent.com/120131543/224106945-ab68d41d-435a-43bb-8ad6-302b8ae9283b.png)
![image](https://user-images.githubusercontent.com/120131543/224106985-f4238119-9883-41e1-b9b3-44e75b9b220d.png)
![image](https://user-images.githubusercontent.com/120131543/224107074-121055ea-ce30-4ec8-9594-eadc236fa2da.png)
![image](https://user-images.githubusercontent.com/120131543/224107109-490caa35-8d3f-44a7-bdd4-de0f9024851e.png)

**Comment by 4z4le4** [comment]
คาดว่าจะต้องปรับรูปแบบการแสดงผลของตัวเลือก ฝากเงินแบบกรอกจับนวน และ การยกเลิกการทำรายกายให้ดูดีมากกว่านี้
รูปแบบเดิมคือ
![image](https://user-images.githubusercontent.com/120131543/224107418-0928b688-7aaf-4b9f-b6f3-cee0250cc8a9.png)
![image](https://user-images.githubusercontent.com/120131543/224107527-bb8cba26-4376-4e5a-8816-4f288b111d0f.png)

**Comment by 4z4le4** [comment]
ในการเปลี่ยนแปลง ปรับรุปแบบการแสดงผล กำลังจะทำนะครับ ขอพักจิบแกฟา กาแฟ ก่อนเด้อค้าบ

**Comment by 4z4le4** [comment]
บัคยอดเงินไม่ตรงกับสลิป ได้ทำการแก้แล้ว เนื่องจากการเรียกใช้สลิป โ๕้ดอญู่ได้บนการเขียนยอดเงินทำให้การเขียนยอดเงินไม่เกิดขึ้นเพราะในส่วนของโค้ดสลีปมีการวนกลับไปที่หน้ามนูก่อนจะเขียนยอดเงิน
![image](https://user-images.githubusercontent.com/120131543/224227291-d5bcda26-86e6-4402-ba06-afb596974b4d.png)
ได้ทำการแก้ไขเรียบร้อยแล้วนะครับ

**Comment by asporQ** [comment]
เพิ่มให้การทำธุกรรมที่ไม่สำเร็จ ผู้ใช้กดย้อนกลับเองได้

**Comment by asporQ** [comment]
ส่วนสร้างaccout ตอนแรกสามารถระบุจำนวนเงินที่ติดลบได้ ให้แก้เป็นระบุจำนวนเงินได้ >= 0

**Comment by 4z4le4** [comment]
> ส่วนสร้างaccout ตอนแรกสามารถระบุจำนวนเงินที่ติดลบได้ ให้แก้เป็นระบุจำนวนเงินได้ >= 0
ทำการแก้ไขโดยการเพิ่มโค้ดดังรูปแล้วครับ
![image](https://user-images.githubusercontent.com/120131543/224231866-1732ef47-c814-404e-a891-408962c89874.png)

หากยอดเงินไม่ถูกต้องจะขึ้นสดงผลดังรูป
![image](https://user-images.githubusercontent.com/120131543/224233455-cd76cf4e-9305-4575-bc17-2644446ab557.png)

**Comment by 4z4le4** [comment]
> เพิ่มให้การทำธุกรรมที่ไม่สำเร็จ ผู้ใช้กดย้อนกลับเองได้

กำลังดำเดินการให้ครับ เบื่องต้นทำในส่วนของการสมัคร และหลังจากสลีปแสดงผลเรียบ้อยแล้วครับ

**Comment by 4z4le4** [comment]
> ล่าสุดทำการแก้ไขเมนูให้มีขขนาดที่เหมาะและกำลังเพิ่ม เมนูกดย้อนกลับครับ

**Comment by 4z4le4** [comment]
ล่าสุดทำการเพิ่มเมนูย้อนกลับ และปรับหน้าต่างการแสดงผล
![image](https://user-images.githubusercontent.com/120131543/224479430-c920e708-8047-4050-9703-121089146388.png)

**Comment by 4z4le4** [comment]
> Reference in n
อัพเดทล่าสุดของเมนูเช็คยอดเงิน
![image](https://user-images.githubusercontent.com/120131543/224479658-ddf1ce77-74c5-4fc8-9b99-a3a1d4c548f5.png)

**Comment by 4z4le4** [comment]
ตอนสมัครแอคเคาท์ทำการเพิ่มการรับชื่อผู้ใช้ไปด้วยแล้วนะครับ
![image](https://user-images.githubusercontent.com/120131543/224493104-9240f833-028a-4736-a323-7b1efff6a524.png)

**Comment by 4z4le4** [comment]
/// การอ่านไฟล์ชื่อ ทางที่ดีควรทำให้มีนามสกุลด้วยจะมีมากเลยนะครับ @Suwannapop

**Comment by asporQ** [comment]
**BUG**
เวลาโอนเงินไปบัญชีปลายทางแล้วปลายทางไม่มีบัญชีที่ว่า  จะขึ้นให้สร้างบัญชี ซึ่งไม่สมเหตุสมผล เลยจะสร้างฟังก์ชันใหม่ที่ใช้กับการเช็คบัญชีปลายทางแยกไปเลย

**Comment by 4z4le4** [comment]
> **BUG** เวลาโอนเงินไปบัญชีปลายทางแล้วปลายทางไม่มีบัญชีที่ว่า จะขึ้นให้สร้างบัญชี ซึ่งไม่สมเหตุสมผล เลยจะสร้างฟังก์ชันใหม่ที่ใช้กับการเช็คบัญชีปลายทางแยกไปเลย

ทำการสร้างฟังก์ชั่นแยกมาเพื่อตรวจเช็คแล้วนะครับ โดยใช้ ImportFile_T ที่ใช้ต้นแบบมาจาก ImportFile ครับ
![image](https://user-images.githubusercontent.com/120131543/224504900-61302854-1122-4a63-8427-f4b3ccaadc2a.png)

**Comment by asporQ** [comment]
### **BUG**

โอนเงินเข้าบัญชีตัวเองแล้วเงินรวมในบัญชีตัวเองเพื่ม

**Comment by 4z4le4** [comment]
> ### **BUG**
> โอนเงินเข้าบัญชีตัวเองแล้วเงินรวมในบัญชีตัวเองเพื่ม

ทำการแก้บัคโดย การทำให้มีการเช็คไอดีที่ป้อนเข้ามา ว่าตรงกับบัญชีปลายทางหรือเปล่าก่อนที่จะทำการโอนนะครับ
![image](https://user-images.githubusercontent.com/120131543/224556866-21611b73-8b5c-4c18-bcc4-d21b85395f2f.png)

**Comment by 4z4le4** [comment]
ล่าสุดระบบ 90% แล้วนะครับเหลือให้ @asporQ เอาตัวโปรแกรมไปปรับแต่งหน้าUIให้ดูดีสวยงามขึ้นครับ ฝากด้วยนะครับ
![image](https://user-images.githubusercontent.com/120131543/224562405-80aa0525-6828-448d-a716-16e9ab4c0659.png)

**Comment by 4z4le4** [comment]
ฝาก @asporQ เพิ่มในส่วนของสลิปใบเสร็จให้มีการแสดงชื่อบัญชีปลายทางที่เราจ่ายบิลด้วยหน่อยนะครับ
![image](https://user-images.githubusercontent.com/120131543/224627788-665d3581-2ac2-4415-83e5-b8d690d0ea31.png)

**Comment by 4z4le4** [comment]
// ทำการแก้ไข UI ทั้งหมด โดยใช้คำสั่ง char() มาใช้ในการสร้าง UI เพื่อให้มีความสวยงามมากขึ้น
สามารถดูได้ในบาร์ทเมนหลักได้เลยนะครับ
ความคืบหน้า 90% โดยประมาณแล้วครับ

**Comment by Fittokung** [comment]
![image](https://user-images.githubusercontent.com/110965124/225241330-b30eb4fe-6abc-4b34-a988-e453261979ce.png)
เปลี่ยนจาก Exit ไปหน้า login --> เป็นกลับไปหน้า Menu ไหม

**Comment by Fittokung** [comment]
![image](https://user-images.githubusercontent.com/110965124/225241729-88a8d17c-02d7-4087-bba7-43e22ae0af7f.png)
Game Top up

**Comment by Fittokung** [comment]
![image](https://user-images.githubusercontent.com/110965124/225243286-a48a5f26-9a36-423f-ac15-1b0a56bd33e9.png)
อันนี้กด enter แล้วมันtapลงมา สามารถแก้ให้มัน reset หน้ากลับมาเรื่อยๆได้ไหม อันนี้ไม่แน่ใจ

**Comment by Fittokung** [comment]
![image](https://user-images.githubusercontent.com/110965124/225243710-c0d0db92-5df1-4fb7-b360-f97bee1ff8ed.png)
ค่าน้ำ,ค่าไฟ,ค่าโทรศัพท์ --> เปลี่ยนคำด้านบนเป็น How much do you want to pay?

**Comment by 4z4le4** [comment]
> ![image](https://user-images.githubusercontent.com/110965124/225243710-c0d0db92-5df1-4fb7-b360-f97bee1ff8ed.png) ค่าน้ำ,ค่าไฟ,ค่าโทรศัพท์ --> เปลี่ยนคำด้านบนเป็น How much do you want to pay?
![image](https://user-images.githubusercontent.com/120131543/225245186-c7b288f1-b258-4ab5-85bb-a7147c8c052f.png)
แก้ให้แล้วนะครับ

**Comment by 4z4le4** [comment]
> ![image](https://user-images.githubusercontent.com/110965124/225241729-88a8d17c-02d7-4087-bba7-43e22ae0af7f.png) Game Top up

![image](https://user-images.githubusercontent.com/120131543/225245994-e38bdfdd-96a6-4a37-891e-5c98753ac810.png)
แก้เขียนให้แล้วนะครับ

**Comment by 4z4le4** [comment]
ส่วนนี้เปลี่ยนเมนูย้อนกลับ มาเป็นเมนูใหม่ ขอติดไว้ก่อน มาพูดตอนนัดประชุมอีกทีนะครับ
ส่วนเรื่อง Enter แก้ไม่ได้ครับเป็นจุดบอร์ดของเทอมินอล ขออภัยด้วยนะครับ แต่จะลองไปไลบรารี่มาลองอีกรอบนะครับ

**Comment by Blackcat2101** [comment]
![แก้1000ไหม](https://user-images.githubusercontent.com/120165342/225292832-ed9dd51a-6a77-4215-b3dc-f66de6a252cc.png)
คิดว่าน่าจะมีตัวเลือกฝากเงิน 1000 ไหม

**Comment by 4z4le4** [comment]
> ![แก้1000ไหม](https://user-images.githubusercontent.com/120165342/225292832-ed9dd51a-6a77-4215-b3dc-f66de6a252cc.png) คิดว่าน่าจะมีตัวเลือกฝากเงิน 1000 ไหม
![image](https://user-images.githubusercontent.com/120131543/225522557-b382a9d3-5176-40d3-99e2-4f1232db5eb9.png)
เพิ่มในส่วนฝากและถอน ในจำนวนเงิน1000แล้วนะครับ

**Comment by 4z4le4** [comment]
ทำการเพิ่มระบบสมัครกับระบบล็อคอินนะครับ เผื่อมีคนต้องการสมัครไอดีใหม่
![image](https://user-images.githubusercontent.com/120131543/225645921-e9c787f4-3e22-4203-a593-9900f7c6f240.png)

**Comment by 4z4le4** [comment]
![image](https://user-images.githubusercontent.com/120131543/225696257-221f8825-687c-40e8-9120-7a6ee8547425.png)
อัพเดทล่าสุดแก้บัคทุกอย่างที่เจอแล้ว+แก้ไขสิ่งแปลกๆหมดแล้วค้าบ ขอปิดissue นี้เลยนะค้าบผม See yaaaa
