### ISSUE TITLE
ทำระบบเช็คยอดเงิน

### ISSUE THREAD

**Issue by 4z4le4** [Suwannapop/ProjectComPro#11]

**Comment by chananchidaily** [comment]
//check balance
#include<iostream>
using namespace std ;
int accnumber ;
float balance ;
cout << "Enter your Account Number" ;
cin << accnumber ;
void deposit()
{
float more; //ยอดฝากกก
cout <<"Depositing";
cout<<"Enter the amount to deposit : "; //อันนี้ฝาก
cin>>more;
balance+=more;
}
void withdraw()
{
float amt; //ยอดถอนง่ะ
cout<<"Withdrwal";
cout<<"Enter the amount to withdraw : "; //อันนี้ถอน
cin>>amt;
balance-=amt;
}

**Comment by asporQ** [comment]
```
//check balance
#include
using namespace std ;
int accnumber ;
float balance ;
cout << "Enter your Account Number" ;
cin << accnumber ;
void deposit()
{
float more; //ยอดฝากกก
cout <<"Depositing";
cout<<"Enter the amount to deposit : "; //อันนี้ฝาก
cin>>more;
balance+=more;
}
void withdraw()
{
float amt; //ยอดถอนง่ะ
cout<<"Withdrwal";
cout<<"Enter the amount to withdraw : "; //อันนี้ถอน
cin>>amt;
balance-=amt;
}
```

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/221395714-c756d7d3-3702-493d-926d-1cd9bf5d9102.png)

**Comment by asporQ** [comment]
ลงsource codeใหม่ป็นไฟล์.txtให้หน่อยค่า รูปแตกอ่านcodeไม่ได้

**Comment by chananchidaily** [comment]
โอเคค่า

**Comment by chananchidaily** [comment]
cout << "Your current balance is: $" << fixed << setprecision(2) <<ID1.money[0] << "\n";
