### ISSUE TITLE
Dataสำหรับใช้ทดสอบ

### ISSUE THREAD

**Issue by asporQ** [Suwannapop/ProjectComPro#13]

**Comment by asporQ** [comment]
[accounts_2.txt](https://github.com/Suwannapop/ProjectComPro/files/10806247/accounts_2.txt)

**Comment by asporQ** [comment]
**data50ชุด**
[accounts.txt](https://github.com/Suwannapop/ProjectComPro/files/10806250/accounts.txt)

**Comment by asporQ** [comment]
data 50 ชุด
[accounts.txt](https://github.com/Suwannapop/ProjectComPro/files/10806420/accounts.txt)

**Comment by asporQ** [comment]
data 2 ชุด
[accounts_2.txt](https://github.com/Suwannapop/ProjectComPro/files/10806426/accounts_2.txt)

**Comment by asporQ** [comment]
data 2 ชุด
[accounts_2.txt](https://github.com/Suwannapop/ProjectComPro/files/10806440/accounts_2.txt)

**Comment by Suwannapop** [comment]
เคครับพี่
ไฟล์ที่อยู่ branch mainที่ชื่อว่า Datafile อันนี้นผมทำเองนะครับ เดี่ยวค่อยเปลี่ยนเอาละกัน

**Comment by Suwannapop** [comment]
ต้องทำไฟล์ เเยกเป็นอันๆเเล้วเอาเเบบบัญชีไหนบัญชีนั้นเลย

**Comment by asporQ** [comment]
สรุป ทำไฟล์.txtแยกของแต่ละบัญชี ซึ่งจะเก็บ [ เลขบัญชี,รหัสบัญชี,จำนวนเงินในบัญชี ]
