### ISSUE TITLE
Bug login

### ISSUE THREAD

**Issue by 4z4le4** [Suwannapop/ProjectComPro#14]
#Bug

**Comment by 4z4le4** [comment]
Bug login 
ถ้ารหัสผ่านถูก แต่ไม่มีdata โปรแกรมจะหยุดทำงาน

**Comment by 4z4le4** [comment]
Bug login
แก้แล้ว
-ทำdataเพิ่มเข้าไป
โดยจากเดิม รหัสนักศึกษา , จำนวนเงิน --เปลี่ยนเป็น--> รหัสนักศึกษา , จำนวนเงิน , รหัสผ่าน

**Comment by 4z4le4** [comment]
Bug TransferMoney
ในระบบโอนเงินเดิมคือ จากสร้างยอดเงินใหม่ทับไปในdataเดิม
หลังจากเพิ่มdataรูปแบบใหม่ ทำให้  รหัสผ่าน ไม่ถูกเขียนไปด้วย
ส่งผลให้เกิด Bug ทำให้ login id เดิมไม่ได้เนื่องจากรหัสผ่านที่บันทึกไว้ใน data หายไป

**Comment by asporQ** [comment]
bug - log in 
ปู้นๆ บัคใหม่ครับ
- เช็คไอดีไม่ได้
- ตัวเช็ครหัสล็อกอินที่ใช้เป็นลบเลข65061000เพื่อเอา4ตัวท้ายเป็นรหัส มันใช้กับไอดีอื่นที่ไม่ใช่รหัสนศ.ปี65ไม่ได้

**Comment by 4z4le4** [comment]
เนื่องจากรูปแบบการ login แบบเดิมคือการใช้รหัสผ่านเป็นการเช็คว่า รหัสผ่านตรงกับเลขหลัง4ตัวท้ายของ id ทำให้มีการจำกัดความของการใช้ ID ในปีอื่นๆนอกจาก 65 จะไม่สามารถใช้งานได้ จึงมีการเปลี่ยนแปลงดดังนี้
![image](https://user-images.githubusercontent.com/120131543/222900069-1894c6f7-56a0-4018-afa8-2f120d5c6e00.png)
- ทำการเปลี่ยนตัวเช็ครหัส จากเดิม ที่คือเอารับค่า id กับ password โดยที่  password = id-65061000 เป็นการเช็ครหัสผ่านในdataที่เก็บไว้ในfile.txt ในรูปแบบ password,id,money

![image](https://user-images.githubusercontent.com/120131543/222900201-e6458f4a-2b17-41b9-910e-e08b0ed4162c.png)
- ทำการเพิ่มในส่วนของการสร้าง id ใหม่โดยครั้งนี้ password ไม่จำเป็นต้องเป็นเลข4ตัวท้ายของ id และสามารถสร้างpasswordได้เอง
- เพิ่มการเช็ค id หาก login โดยมี id อยู่ในdata เมื่อ password ผิดจะมีการขึ้นเตือนดั่งรูป 
![image](https://user-images.githubusercontent.com/120131543/222900336-130432e4-5336-4724-9c78-684619f7710d.png)
แต่ถ้าหากไม่มี id ในdata จะมีการขึ้นแจ้งเตือนให้สร้าง id ใหม่
![image](https://user-images.githubusercontent.com/120131543/222900415-3a923cf4-edc6-4f41-938c-acb0c406158b.png)


[การใช้ภาษาอาจจะยังไม่ถูกต้อง]
