### ISSUE TITLE
Bug TransferMoney

### ISSUE THREAD

**Issue by 4z4le4** [Suwannapop/ProjectComPro#16]
Bug TransferMoney
ในระบบโอนเงินเดิมคือ จากสร้างยอดเงินใหม่ทับไปในdataเดิม
หลังจากเพิ่มdataรูปแบบใหม่ ทำให้ รหัสผ่าน ไม่ถูกเขียนไปด้วย
ส่งผลให้เกิด Bug ทำให้ login id เดิมไม่ได้เนื่องจากรหัสผ่านที่บันทึกไว้ใน data หายไป

**Comment by 4z4le4** [comment]
เพื่อนต้นแก้บัคตอนโอนเงินด้วยนะครับ

**Comment by Suwannapop** [comment]
ได้เลยครับพี่ชาย

**Comment by Suwannapop** [comment]
ทำให้อ่านไฟล์ได้เเล้ว

**Comment by asporQ** [comment]
bug transfer
เขียนไฟล์แบบใช้แล้วไฟล์ไม่อัพเดตตาม

**Comment by 4z4le4** [comment]
> bug transfer เขียนไฟล์แบบใช้แล้วไฟล์ไม่อัพเดตตาม

![image](https://user-images.githubusercontent.com/120131543/222899799-736d0942-7f65-4f08-97b3-024606e5209e.png)
ได้เพิ่มให้เขียนค่าเงินเรียบร้อยแล้วครับ เนื่องจากcodeเดิมไม่ได้มีการเพิ่มในส่วนของรหัสผ่านไว้ จึงเกิดการเก็บของข้อมูลในรูปแบบดั่งเดิม แต่ตอนนี้ได้อัพเดทให้มีเข้ากันกับทุกฟังก์ชั่นแล้วครับ
