### ISSUE TITLE
รายงาน Bug

### ISSUE THREAD

**Issue by Suwannapop** [Suwannapop/ProjectComPro#17]

**Comment by 4z4le4** [comment]
![image](https://user-images.githubusercontent.com/120131543/222459084-273a42bd-6ab7-421d-a090-a137132a1151.png)
ตรงเช็คยอดเงินบัคนะครับ ตอนที่สร้างไอดีใหม่เข้าไปแล้วจะเช็คยอดเงิน ขึ้นบัคตามรูปเลยนะ ฝากคนรับผิดชอบเรื่องเช็คยอดเงิน เช็คแล้วแก้ไขด้วยนะครับ

**Comment by Suwannapop** [comment]
![image](https://user-images.githubusercontent.com/110958686/222497825-a2a730eb-33be-4ceb-a39a-9cdebe29c27c.png)
bug ตรง โอนเงินตอนที่ใส่ ID ปลายทาง ถ้าเราใส่ ID ปลายทางมันต้องขึ้นว่าไม่เจอ Data หรืออะไรทำนองนั้นเเต่อันนี้ มันให้สร้างงบัยชีใหม่ สึ่งการสร้างบัญชีใหม่ต้องทำในขั้นตอน login ครั้งเเรกเท่านั้น

เดี่ยวอันนี้ทำเองไม่ยากๆ

**Comment by 4z4le4** [comment]
> ![image](https://user-images.githubusercontent.com/120131543/222459084-273a42bd-6ab7-421d-a090-a137132a1151.png) ตรงเช็คยอดเงินบัคนะครับ ตอนที่สร้างไอดีใหม่เข้าไปแล้วจะเช็คยอดเงิน ขึ้นบัคตามรูปเลยนะ ฝากคนรับผิดชอบเรื่องเช็คยอดเงิน เช็คแล้วแก้ไขด้วยนะครับ

ตรงนี้แก้แล้วนะครับ
![image](https://user-images.githubusercontent.com/120131543/222632217-991ea0d1-a71a-4d0d-8c68-55a9c3031e7a.png)
บัคเกิดจากตัวของการเขียนไฟล์มีการใส่ค่าช่องว่าง ที่เกินมาโดยไม่จำเป็น จึงทำให้เกิดบัค ตอนนี้ได้ทำการแก้บัคแล้วนะครับ

**Comment by Fittokung** [comment]
บัคระบบฝากเงิน (Deposition)
- เมื่อฝากเงินแล้ว ยอดเงินใน data base ไม่เปลี่ยนแปลงตาม -> แก้โดยการส่งค่าคืนในทุก ๆ case ที่มีการฝากเงิน
- เมื่อยอดฝากมีค่ามาก ๆ จะติดค่าเป็นสัญกรณ์วิทยาศาสตร์ -> แก้โดยการ change position

### แก้บัคแล้ว ###

**Comment by 4z4le4** [comment]
ขอปิดIssueนี้นะค้าบ
