### ISSUE TITLE
bug withdraw

### ISSUE THREAD

**Issue by asporQ** [Suwannapop/ProjectComPro#18]

**Comment by asporQ** [comment]
โอนไม่ได้ หาจำนวนเงินไม่ได้ อัพเดตโค้ดให้ตามเวอร์ชันใหม่ที่แก้บัคไปแล้วด้วย

**Comment by 4z4le4** [comment]
> โอนไม่ได้ หาจำนวนเงินไม่ได้ อัพเดตโค้ดให้ตามเวอร์ชันใหม่ที่แก้บัคไปแล้วด้วย
![image](https://user-images.githubusercontent.com/120131543/222899604-3261b1b7-5075-4a0d-a557-53c99d001d47.png)
โอนได้ตามปกติแล้วนะครับ แก้ในส่วนของ void Withdraw(double amount, Dataformat ID) --> void Withdraw(double amount, Dataformat &ID1) และ  ID เป็น ID1 ในทุกๆส่วนของฟังก์ชั่น Withdraw

**Comment by asporQ** [comment]
เจอบัคตอนที่ป้อนจำนวนเงินที่ต้องการเข้าไปแล้วมากกว่าเงินในบัญชีค่าจะติดลบ
![image](https://user-images.githubusercontent.com/120199524/223784561-74de2fe1-e813-4b43-a4aa-73cce2754ba8.png)

**Comment by asporQ** [comment]
แก้เป็นเช็คผลต่างในบัญชีว่าติดลบมั้ย ถ้าติดให้แสดงข้อความว่า "Invalid! or your money not enough, Please try again." แทน
![image](https://user-images.githubusercontent.com/120199524/223785718-d573e861-08f0-4d7a-9a83-e9d555dfa480.png)

**Comment by asporQ** [comment]
![image](https://user-images.githubusercontent.com/120199524/223791058-4232bf1c-190d-4e55-a97b-b6bfca6c219e.png)
![image](https://user-images.githubusercontent.com/120199524/223791138-1c61f643-7adf-49d9-8f15-b1a21df9b160.png)
แก้ใหม่ๆ ตัวด้านล่างแก้conditionใหม่
