### ISSUE TITLE
เพิ่มฟังก์ชันโปรแกรม

### ISSUE THREAD

**Issue by asporQ** [Suwannapop/ProjectComPro#19]
- จ่ายค่าน้ำ,ค่าไฟ
- สลีปเงินสด หลังจากทำธุรกรรมเสร็จ
- sound
- ชื่อบัญชี

**Comment by asporQ** [comment]
แจงงาน
- จ่ายบิล [ จ่ายค่าน้ำ ค่าไฟ เติมเงิน ] = @santhod  @Fittokung 
- เพิ่มเมนูชื่อบัญชี = @chananchidaily @Suwannapop 
- สลีปเงินสด = @asporQ 
- sound = @asporQ

**Comment by asporQ** [comment]
> แจงงาน
> 
> * จ่ายบิล [ จ่ายค่าน้ำ ค่าไฟ เติมเงิน ] = @santhod  @Fittokung *waiting
> * เพิ่มเมนูชื่อบัญชี = @chananchidaily @Suwannapop✅
> * สลีปเงินสด = @asporQ ✅
> * sound = @asporQ

**Comment by 4z4le4** [comment]
10/3/2556
เหลือ จ่ายบิลนะครับ ที่ยังไม่ได้อัพเดทเข้าไปในฟังก์ชั่นหลัก

**Comment by 4z4le4** [comment]
ขอปิด issue นี้นะครับ เนื่องจากมี issue ส่วนของารจ่ายบิลไว้ และเหลือแค่ฟังก์ชั่นเดียว
