### ISSUE TITLE
เสียง

### ISSUE THREAD

**Issue by asporQ** [Suwannapop/ProjectComPro#22]

**Comment by 4z4le4** [comment]
ขอพักเรื่องการเพิ่มเสียงไว้ก่อนนะครับ เนื่องจากไม่ค่อยจำเป็นและมีบัคเยอะเกินไป

**Comment by 4z4le4** [comment]
คิดว่าไม่จำเป็นในตอนนี้ เน้นไปที่การแต่งUIดีกว่านะครับ ขอปิดissueนี้นะครับ
