### ISSUE TITLE
ตรวจโค้ดครั้งที่1และสิ่งที่ต้องแก้ไข

### ISSUE THREAD

**Issue by chananchidaily** [Suwannapop/ProjectComPro#25]
1. บรรทัด 26, 42, 58, 79 เขียน คำว่า Receipt ที่แปลว่า ใบเสร็จผิด ซึ่งในโค้ดเขียนเป็นRECIRPT ต้องเปลี่ยน ir เป็น ei
2. บรรทัด 488 ลืมใส่ t ตรงคำว่า account
3. บรรทัด 465, 472, 534, 531 เขียนคำว่า balance ที่แปลว่ายอดเงินผิด  ในโค้ดเขียนเป็น  balnace
4. 382, 813 มันต้องใช้ How much ไม่ใช่ How many เพราะใช้กับเงินตามหลัก grammar เงินนับไม่ได้
5. 577, 864  Now you have ควรมีกรรมมารับ เช่น Now you have itม Now you have money  
6. 127, 489 ใส่ Do ด้วย
7. 541 Database ใส่ e ตรงท้ายด้วย
8. 278, 711 คำว่า cancel ที่แปลว่ายกเลิกผิด ในโค้ดเขียนเป็นcancal

**Comment by chananchidaily** [comment]
9. 580 ใส่ Do ด้วย

**Comment by chananchidaily** [comment]
จากการตรวจโค้ด 984 บรรทัด พบว่า ไวทยากรณ์ในภาษา c++ มีความถูกต้อง แต่มีข้อผิดพลาดในการใช้คำ ทั้งการใช้คำไม่เหมือนกันทั้งที่เป็นตัวแปรที่สื่อความหมายเหมือนกันและการพิมพ์ผิดในบางบรรทัดทำให้ผู้อ่านอาจจะสับสนและไม่เข้าใจในสิ่งที่ต้องการจะสื่อ

**Comment by 4z4le4** [comment]
ปิดละเด้อแก้ละครับ
