### ISSUE TITLE
เเก้ warning ที่เตือนมาใน  Terminal ตอน Run

### ISSUE THREAD

**Issue by Suwannapop** [Suwannapop/ProjectComPro#27]
![image](https://user-images.githubusercontent.com/110958686/224709515-24bbad12-935a-430b-8124-a7f31afec278.png)

![image](https://user-images.githubusercontent.com/110958686/224709466-476c8b14-97f7-4887-856a-8e0a7c9e7be2.png)

เดียวโดนพี่ TA จวก
มี บรรทัดที่ 492 ,502 ,555, 557 , 814 ,825 ,839 ,916 ,930 ,1276 ,1558 ,1861 ,2008 ,2034

**Comment by Suwannapop** [comment]
เหลือ 
![image](https://user-images.githubusercontent.com/110958686/224710646-535a75d5-2802-4227-b80e-5ac0254f6e8e.png)
มันอยู่ในฟังชั่นไม่กล้าทำเดียวไปโดนระบบ ไม่รู้เป็นของใครด้วยอะสิ

**Comment by 4z4le4** [comment]
แก้ให้แล้วนะครับ ขอปิดissue นี้นะครับ
