### ISSUE TITLE
ตรวจคำครั้งที่2

### ISSUE THREAD

**Issue by chananchidaily** [Suwannapop/ProjectComPro#28]
1.1046 1055 1058 1069 1072 1136 1145 1148 1159 1162  balance ที่แปลว่ายอดเงิน balnace  ไม่มีความหมายงับบ
2.860 1638 amount เขียนผิดค่ะ
3.512 1087 1248 ใส่ Do  ข้างหน้าให้หน่อยน้า ละ want ตัวพิมพ์เล็กให้หน่อย
4.1083 1173 database ผิด

**Comment by 4z4le4** [comment]
> 1.1046 1055 1058 1069 1072 1136 1145 1148 1159 1162 balance ที่แปลว่ายอดเงิน balnace ไม่มีความหมายงับบ 2.860 1638 amount เขียนผิดค่ะ 3.512 1087 1248 ใส่ Do ข้างหน้าให้หน่อยน้า ละ want ตัวพิมพ์เล็กให้หน่อย 4.1083 1173 database ผิด

1. ในส่วนนี้เป็นค่าตัวแปร ขอไม่แก้นะ ไม่ได้มีผลบนตัว ui
2. แก้ให้แล้ว
3. แก้ให้แล้ว
4. แก้ให้แล้ว
ขอปิดนะครับ
