### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Suwannapop** [Suwannapop/ProjectComPro#29]

**Comment by Suwannapop** [comment]
![image](https://user-images.githubusercontent.com/110958686/225292857-5ae2325e-3992-4408-8380-dc8f54b25b64.png)
Deposit 200 บาทไม่ได้ทำการเขียนลงในไฟล์ทำให้ข้อมูลในส่งนของตังไม่เปลี่ยน

**Comment by Suwannapop** [comment]
![image](https://user-images.githubusercontent.com/110958686/225294505-b1b140bc-25fa-4fa3-8792-33b9299c9e30.png)
in put Name เเบบเว้นบรรทัดเเล้วมันเอานามสกุลไปเป็น Password

**Comment by Blackcat2101** [comment]
อันนี้ก๋องบอกว่าให้ใช้ _คั่นแทนเว้นวรรค

**Comment by Suwannapop** [comment]
เคๆ

**Comment by Suwannapop** [comment]
ที่เหลือก็ไม่มีเเล้ว

**Comment by Blackcat2101** [comment]
![bug ฝาก 500000](https://user-images.githubusercontent.com/120165342/225295654-e159fccd-a487-4deb-82af-ce6bdb655286.png)
มันบัคป้ะเวลา ฝากไป 500000 แล้ว ในบัญชีมันขึ้นหลักล้านแบบนั้น

**Comment by Suwannapop** [comment]
ไม่ๆ
ลองกดเข้าในบัญชีว่ามีเท่าไหล่มันก็เเสดงเหมือนเดิม
![image](https://user-images.githubusercontent.com/110958686/225296531-21fdf63c-7856-48ae-a61c-47f789f2a69a.png)
ต้องกดอันนี้มันจะเเสดงเงินปกติ 
ตอนใช้เราจะไม่ เข้าไปดูในไฟล์เลย

**Comment by Blackcat2101** [comment]
เค

**Comment by Blackcat2101** [comment]
![ฝากไปเป็นจุด ใบเสร็จขึ้น แต่ในบาล้านไม่ขึ้น](https://user-images.githubusercontent.com/120165342/225298408-6c5a2b0e-8073-4389-85a8-300b2238873b.png)
ฝากไปเป็นจุดทสนิยม ในใบเสร็จขึ้นนะ แต่ใน Balance ไม่ขึ้นทศนิยม
![ในbalance](https://user-images.githubusercontent.com/120165342/225298683-23a9c8f3-3b03-4644-ac9a-4f5255362d58.png)

**Comment by Blackcat2101** [comment]
![image](https://user-images.githubusercontent.com/120165342/225299504-d9c76f30-83c0-40d3-90c0-5b9f4a8120db.png)
ถ้าแบบมีเครื่องหมาย +,- ยอดเงินมันเอาตัวเลขแรกมาคิด และเวลากลับไปหน้า login มันขึ้นแบบด้านล่าง(แต่ใครมันจะมาฝากเงินมีเครื่องหมาย)
![image](https://user-images.githubusercontent.com/120165342/225299694-298904c3-d21d-4d89-8580-5c4892c42739.png)
![image](https://user-images.githubusercontent.com/120165342/225299810-33c269ff-247d-4c66-8502-ac4c2afc2e2e.png)

**Comment by Suwannapop** [comment]
![image](https://user-images.githubusercontent.com/110958686/225301726-bef943ad-82fc-4a5a-9d5c-363789abe825.png)
![image](https://user-images.githubusercontent.com/110958686/225301669-4c03da9f-5eee-4aaa-b338-b4d3e9665264.png)
WaterBill มีปัญหาไม่เเสดงหน้า สลีปมาให้
เเละไม่มีการเขียรไฟล์อะไรเลยทั้งไฟล์ User ที่ login เเละไฟล์ Water
เหมือนมันไม่ทำงานอะไรเลย

**Comment by 4z4le4** [comment]
![image](https://user-images.githubusercontent.com/120131543/225378408-7aa9b5ae-2981-43e6-9d4b-c23bac66b4da.png)
แก้ให้แล้วนะค้าบ
