### ISSUE TITLE
Bug || :Deposit เฉพาะ 200 บาทไม่ได้ทำการเขียนลงในไฟล์ทำให้ข้อมูลในส่งนของตังไม่เปลี่ยน

### ISSUE THREAD

**Issue by Suwannapop** [Suwannapop/ProjectComPro#31]
![image](https://user-images.githubusercontent.com/110958686/225292857-5ae2325e-3992-4408-8380-dc8f54b25b64.png)
Deposit 200 บาทไม่ได้ทำการเขียนลงในไฟล์ทำให้ข้อมูลในส่งนของตังไม่เปลี่ยน

_Originally posted by @Suwannapop in https://github.com/Suwannapop/ProjectComPro/issues/29#issuecomment-1469815480_

**Comment by 4z4le4** [comment]
![image](https://user-images.githubusercontent.com/120131543/225378677-1bb3d4b0-a5c3-41b7-880d-8ea24ceee5a6.png)
แก้ให้แล้วนะค้าบ
