### ISSUE TITLE
Bug || : WaterBill มีปัญหาไม่เเสดงหน้า สลีปมาให้ เเละไม่มีการเขียรไฟล์อะไรเลยทั้งไฟล์ User ที่ login เเละไฟล์ Water เหมือนมันไม่ทำงานอะไรเลย

### ISSUE THREAD

**Issue by Suwannapop** [Suwannapop/ProjectComPro#32]
![image](https://user-images.githubusercontent.com/110958686/225301726-bef943ad-82fc-4a5a-9d5c-363789abe825.png)
![image](https://user-images.githubusercontent.com/110958686/225301669-4c03da9f-5eee-4aaa-b338-b4d3e9665264.png)
WaterBill มีปัญหาไม่เเสดงหน้า สลีปมาให้
เเละไม่มีการเขียรไฟล์อะไรเลยทั้งไฟล์ User ที่ login เเละไฟล์ Water
เหมือนมันไม่ทำงานอะไรเลย

_Originally posted by @Suwannapop in https://github.com/Suwannapop/ProjectComPro/issues/29#issuecomment-1469868514_

**Comment by 4z4le4** [comment]
![image](https://user-images.githubusercontent.com/120131543/225387404-30f35b7e-63a2-410b-8054-4a8f677882dc.png)
แก้ให้แล้วนะครับ
