### ISSUE TITLE
ทำระบบ ฝาก

### ISSUE THREAD

**Issue by Suwannapop** [Suwannapop/ProjectComPro#7]

**Comment by Fittokung** [comment]
อยู่ระหว่างการทดลองระบบ

**Comment by Fittokung** [comment]
Data ที่นำมาใช้ในการทดสอบ
650610001 6800
650610002 6001

**Comment by Fittokung** [comment]
[deposit.txt](https://github.com/Suwannapop/ProjectComPro/files/10831343/deposit.txt)

**Comment by Fittokung** [comment]
ใช้ Data [650612100, 9500] ในการทดสอบ
สามารถเลือกจำนวนเงินฝากได้ 5 ทางเลือก
- $20
- $50
- $100
- $200
- $500

**Comment by Suwannapop** [comment]
ทำให้มัน importfile ของfileของuser นั้นๆมาเเล้วเขียนทับเข้าไปเลยได้ไหม

**Comment by Fittokung** [comment]
[deposit.txt](https://github.com/Suwannapop/ProjectComPro/files/10847668/deposit.txt)

**Comment by 4z4le4** [comment]
ผม เอาโค้ดจาก branches Deposit
[ProjectComPro](https://github.com/Suwannapop/ProjectComPro/tree/Deposit)
มารวมไว้ใน UI-MAIN แล้วนะครับ

**Comment by 4z4le4** [comment]
โดยรวมแล้วโค้ดทำรันได้ ทำงานปกติไม่มีบัคใดๆครับ

**Comment by asporQ** [comment]
completed ขออนุญาตปิดนะคะ
