### ISSUE TITLE
ทำระบบ โอน

### ISSUE THREAD

**Issue by Suwannapop** [Suwannapop/ProjectComPro#9]

**Comment by Suwannapop** [comment]
ทำได้ส่วนนึงเเล้วนะครับผมมม

**Comment by Suwannapop** [comment]
ระบบการโอน ทำเป็นไฟล์เเยกกันละหว่าง ไฟล์ผู้โอรกับไฟล์ผู้รับนะ

**Comment by Suwannapop** [comment]
เเล้วให้ input บัญชีต้นเริ่มเเล้วต่อโดยจะโอนไปไหน

**Comment by Suwannapop** [comment]
เเต่ถ้าไฟล์ ผู้ใช้ input บัญชีที่ไม่มีอยู่จริงๆ จะมีปัญหาตรงนี้อยู่

**Comment by Suwannapop** [comment]
อยู่ใน branch TranferMoney

**Comment by Suwannapop** [comment]
ทำให้อ่าน Password จากไฟล์เเล้วเก็บไว้ในตัวเเปลได้เเล้ว

**Comment by Suwannapop** [comment]
![สกรีนช็อต_25660228_001514](https://user-images.githubusercontent.com/110958686/221633062-4e9b9937-2cfe-4bd8-9a8a-d4eac4436573.png)
เเก้ bug ส่งเงินผิดบัญชี เเล้วนะ

**Comment by 4z4le4** [comment]
เจอ bug คับเพื่อนต้น ตรงฟังก์ชั่นที่เพื่อนต้นสร้าง ในการเช็คไฟล์ ลองเพิ่มเงื่อนไขหากไม่พบไฟล์ให้เรียกชั่นฟังกช์ Login_failed(); หน่อยครับ
bug ที่เจอคือเวลาล็อคอินแล้วไม่มีdata โปรแกรมจะหยุดทำงานครับ

**Comment by Suwannapop** [comment]
ได้ครับพี่สวยครับผม

**Comment by 4z4le4** [comment]
![image](https://user-images.githubusercontent.com/120131543/221775309-1ef33f14-9a9e-4053-82f1-609fa3b97f5c.png)
Bug ตรงจุดนี้นะครับ

**Comment by Suwannapop** [comment]
<img width="588" alt="ภาพถ่ายหน้าจอ 2566-02-28 เวลา 13 46 27" src="https://user-images.githubusercontent.com/110958686/221775436-5dda95be-e623-4641-ad1c-2fd8fe719371.png">
ผมลองทำเเบบนี้ดูนะครับ ถ้าหาไฟล์ไม่เจอ ก็ให้ cout  หาไฟล์ไม่เจอนะครับเดี่ยว push ลง branch เเล้วเดี่ยวไปเเก้ใน main อีกที

**Comment by Suwannapop** [comment]
เดียวจะเเตกบ้านใหม่

**Comment by 4z4le4** [comment]
ผ่านแล้วนะครับ ผมขอปิด Issue นี้นะครับ
